public with sharing class Mastodon_Account {
    public Integer id;
    public String username;
    public String acct;
    public String display_name;
    public Boolean locked;
    public DateTime created_at;
    public Integer followers_count;
    public Integer following_count;
    public Integer statuses_count;
    public String note;
    public String url;
    public String avatar;
    public String avatar_static;
    public String header;
    public String header_static;
}